scene1:
  # Number of nodes of the trajectory
  T: 20

  # Time step between each node
  dt: 0.1

  # Initial configuration
  INITIAL_CONFIG: 
    - -0.06709294
    - 1.35980773
    - -0.81605989
    - 0.74243348
    - 0.42419277
    - 0.45547585
    - -0.00456262

  # Initial velocity
  INITIAL_VELOCITY: 
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

  # Target pose
  TARGET_POSE:
    angle: [ 1, 0, 0, 0 ]
    translation: 
      - 0
      - 0.5
      - 1.2

  # Control parameters
  ksi: 0.0001
  di: 0.001
  ds: 0.000001 # 0.0000001

  # Weights
  WEIGHT_uREG: 0.0001
  WEIGHT_xREG: 0.1
  WEIGHT_GRIPPER_POSE: 5
  WEIGHT_GRIPPER_POSE_TERM: 100
  WEIGHT_LIMIT: 0.1

  # Safety threshold
  SAFETY_THRESHOLD: 0

  DIM_OBS:
  - [0.1, 0.2, 0.1]
  DIM_ROB:
  - [0.04, 0.04, 0.04]

  collision_pairs:
    - [el1, el2]


scene2:
  # Number of nodes of the trajectory
  T: 30

  # Time step between each node
  dt: 0.05

  # Initial configuration and velocity
  INITIAL_CONFIG:
    - 6.87676046e-02
    - 1.87133260
    - -9.23646871e-01
    - 6.62962572e-01
    - 5.02801754e-01
    - 1.696128891e-00
    - 4.77514312e-01
  INITIAL_VELOCITY:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

  # Target pose
  TARGET_POSE:
    angle: [ 1, 0, 0, 0 ]
    translation: 
      - 0
      - 0.2
      - 0.9

  # Control parameters
  ksi: 0.1
  di: 0.1 
  ds: 0.0000001

  # Weights
  WEIGHT_uREG: 0.0001
  WEIGHT_xREG: 0.1
  WEIGHT_GRIPPER_POSE: 50
  WEIGHT_GRIPPER_POSE_TERM: 300
  WEIGHT_LIMIT: 0.1

  # Safety threshold
  SAFETY_THRESHOLD: 0

  # Dimensions for obstacles
  DIM_OBS:
    - [0.09, 0.06, 0.2]
    - [0.09, 0.06, 0.2]
    - [0.09, 0.06, 0.2]
    - [0.09, 0.06, 0.2]

  # Dimensions for robot parts
  DIM_ROB:
    - [0.1, 0.08, 0.15]
    - [0.04, 0.06, 0.04]


scene3:
  # Number of nodes of the trajectory
  T: 10

  # Time step between each node
  dt: 0.1

  # Initial configuration
  INITIAL_CONFIG:
    - -0.06709294
    - 1.35980773
    - -0.81605989
    - 0.74243348
    - 0.42419277
    - 0.45547585
    - -0.00456262

  # Initial velocity (all zeros)
  INITIAL_VELOCITY:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

  # Initial state vector
  x0:
    - -0.06709294
    - 1.35980773
    - -0.81605989
    - 0.74243348
    - 0.42419277
    - 0.45547585
    - -0.00456262
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

  DIM_OBS:
  - [0.1, 0.2, 0.1]
  DIM_ROB:
  - [0.04, 0.04, 0.04]

  # Target pose
  TARGET_POSE:
    angle: [ 1, 0, 0, 0 ]
    translation:
      - 0
      - 0.12
      - 1.3

  # Control parameters
  ksi: 0.0001
  di: 0.1  # 1e-4
  ds: 0.0001

  # Weights
  WEIGHT_uREG: 0.0001
  WEIGHT_xREG: 0.1
  WEIGHT_GRIPPER_POSE: 5
  WEIGHT_GRIPPER_POSE_TERM: 100
  WEIGHT_LIMIT: 0.1

  # Safety threshold
  SAFETY_THRESHOLD: 0



scene4:
  # Number of nodes of the trajectory
  T: 20

  # Time step between each node
  dt: 0.1

  # Initial configuration
  INITIAL_CONFIG:
    - -0.8374
    - 1.7468
    - 0.0982
    - 0.8557
    - 1.8011
    - 1.0581
    - -0.0076

  # Initial velocity (all zeros)
  INITIAL_VELOCITY:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

  # Initial state vector
  x0:
    - -0.8374
    - 1.7468
    - 0.0982
    - 0.8557
    - 1.8011
    - 1.0581
    - -0.0076
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

  DIM_OBS:
  - [0.1, 0.2, 0.1]
  DIM_ROB:
  - [0.04, 0.04, 0.04]


  # Target pose
  TARGET_POSE:
    rotation: "x"
    angle: [ 1, 0, 0, 0 ]
    translation:
      - -0.1
      - 0.12
      - 1.3

  # Control parameters
  ksi: 0.0001
  di: 0.1  # 1e-4
  ds: 0.0001

  # Weights
  WEIGHT_uREG: 0.0001
  WEIGHT_xREG: 0.1
  WEIGHT_GRIPPER_POSE: 5
  WEIGHT_GRIPPER_POSE_TERM: 100
  WEIGHT_LIMIT: 0.1

  # Safety threshold
  SAFETY_THRESHOLD: 0
